Fix wrong dep semver range of graphql tools/utils (#6973)
* bump required version of @graphql-tools/utils

otherwise we get this one:
```
$ graphql-codegen --config codegen.yml
/home/capaj/work-repos/authier-repos/authier/node_modules/@graphql-codegen/plugin-helpers/index.js:502
const getCachedDocumentNodeFromSchema = utils.memoize1(utils.getDocumentNodeFromSchema);
                                              ^

TypeError: utils.memoize1 is not a function
    at Object.<anonymous> (/home/capaj/work-repos/authier-repos/authier/node_modules/@graphql-codegen/plugin-helpers/index.js:502:47)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> (/home/capaj/work-repos/authier-repos/authier/node_modules/@graphql-codegen/cli/bin.js:29:23)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
```

* added change set